@startuml
entity ユーザー {
  * ユーザーID
  --
  * ハンドルネーム
}

entity 有効ユーザー {
  * 有効ユーザーID
  --
  * ユーザーID
  * ログインID
  * パスワード
  * 個人情報
}

entity 投稿 {
  * 投稿ID
  --
  * ユーザーID
  * 投稿内容
}

投稿 }o-|| ユーザー
ユーザー ||-o| 有効ユーザー
@enduml